#pragma once

const UINT32 MAX_CLIENT_THREADS = 10;
const UINT32 MAX_CLIENT_FRAME_BUFFER = 1;
#ifdef UNDER_CE
const UINT32 MAX_CLIENT_FRAME_BUFFER_CHUNCK = 3;
#else
const UINT32 MAX_CLIENT_FRAME_BUFFER_CHUNCK = 5;
#endif
const UINT32 MAX_CLIENT_THREADS_READER = MAX_CLIENT_FRAME_BUFFER * MAX_CLIENT_FRAME_BUFFER_CHUNCK;
#ifndef UNDER_CE
const UINT32 MAX_CLIENT_THREADS_READER2 = 50;
const UINT32 MAX_CLIENT_THREADS_POOLED = 800;
const UINT32 MAX_CLIENT_MGT_THREADS_POOLED = 15;
#else
const UINT32 MAX_CLIENT_THREADS_READER2 = 25;//120;
#ifndef USE_NETWORK_PACKET
const UINT32 MAX_CLIENT_THREADS_POOLED = 200;
#endif
const UINT32 MAX_CLIENT_MGT_THREADS_POOLED = 15;
#endif

const UINT32 MAX_CLIENT_THREADS_READER2_CHUNCKS = 1;
#ifndef UNDER_CE
const UINT32 MAX_CLIENT_THREADS_READER3 = 50;
#else
const UINT32 MAX_CLIENT_THREADS_READER3 = 50;
#endif

const UINT32    MAX_SAMPLE_SEQ_NBR_INCR             = 1;//10;
const UINT32    MAX_SAMPLE_ARRAY_SIZE               = 10;
const UINT32    MAX_SAMPLE_ARRAY_BUFFER_THRESHOLD   = 5;

const UINT8     MAX_VIDEO_NETWORK_PACKETS           = 2;
const UINT8     MAX_AUDIO_NETWORK_PACKETS           = 6;
const UINT8     MAX_MGMT_NETWORK_PACKETS            = 1;

const UINT32    MAX_VIDEO_WSARECVFROM_THREADS       = 1;
const UINT32    MAX_VIDEO_WSARECVFROM_BUFFER_SIZE   = 100;
const UINT32    MAX_VIDEO_WSARECVFROM_POOL_THREADS  = 50;
const UINT32    MAX_VIDEO_IOCP_THREADS              = MAX_VIDEO_WSARECVFROM_BUFFER_SIZE * MAX_VIDEO_WSARECVFROM_THREADS;
const UINT32    MIN_VIDEO_WSARECVFROM_POOL_THREADS  = 10;
const UINT32    MAX_VIDEO_WSASENT_BUFFER_SIZE       = MAX_VIDEO_IOCP_THREADS * 4;
const UINT32    MAX_VIDEO_WSASEND_BUFFER_SIZE_BYTES     = 10;

const UINT32    MAX_VIDEO_WSASENDTO_THREADS         = 1;
const UINT32    MAX_VIDEO_WSASENDTO_BUFFER_SIZE     = 100;
const UINT32    MAX_VIDEO_WSASENDTO_POOL_THREADS    = 50;
const UINT32    MAX_VIDEO_IOCP_SENDTO_THREADS       = MAX_VIDEO_WSASENDTO_BUFFER_SIZE * MAX_VIDEO_WSASENDTO_THREADS;
const UINT32    MIN_VIDEO_WSASENDTO_POOL_THREADS    = 10;

const USHORT    HOST_VIDEO_PORT                     = 23499; 
const USHORT    HOST_AUDIO_PORT                     = 23498;
const USHORT    HOST_MANAGEMENT_PORT                = 23497;

const UINT8	    MACADDRESS_LENGTH                   = 40;//39; //modified to accomodate GUID instead of actual MAC Address 24;

const unsigned int PROP_NUM                         = 2;

