/****** Object:  Table [dbo].[utSession]    Script Date: 08/27/2008 14:35:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[utSession](
	[InUseID] [int] NOT NULL DEFAULT ('0'),
	[AvailableID] [int] NOT NULL DEFAULT ('0'),
	[Available] [int] NOT NULL DEFAULT ('0'),
 CONSTRAINT [PK_utSession] PRIMARY KEY CLUSTERED 
(
	[InUseID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
