/****** Object:  Table [dbo].[utEventType]    Script Date: 08/27/2008 14:35:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[utEventType](
	[ID] [int] NOT NULL DEFAULT ((0)),
	[Name] [nvarchar](50) NOT NULL DEFAULT ('Name'),
	[Threshold] [int] NOT NULL DEFAULT ((0)),
	[Retry] [int] NOT NULL DEFAULT ((0)),
 CONSTRAINT [PK_utEventType] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
