#pragma once


enum BLXWARE_EVENT_TYPE : UINT16
{
	BET_MANAGEMENT						= 0
	, BET_VIDEO_STREAM					= 1
	, BET_AUDIO_STREAM					= 2
	, BET_SERVER						= 10000
	, BET_SERVER_ALL_UDP				= 10001
};

enum BLXWARE_EVENT : UINT16
{
	BE_ESTABLISH_VIDEO_SOURCE				= 0
	, BE_REMOVE_VIDEO_SOURCE				= 1
	, BE_ESTABLISH_AUDIO_SOURCE				= 2
	, BE_REMOVE_AUDIO_SOURCE				= 3
	, BE_ESTABLISH_VIDEO_SUBSCRIPTION		= 4
	, BE_REMOVE_VIDEO_SUBSCRIPTION			= 5
	, BE_PUBLISH_VIDEO_FRAME				= 6
	, BE_PUBLISH_AUDIO_SAMPLE				= 7
	, BE_KEEP_ALIVE							= 8
	, BE_DROP_USER_FROM_CONFERENCE			= 9
    , BE_PUBLISH_VIDEO_FRAMES               = 16
    , BE_PUBLISH_AUDIO_FRAMES               = 17
	, BE_INSERT_PPT_VIDEO_SOURCE			= 10000
	, BE_INSERT_PPT_AUDIO_SOURCE			= 10001
	, BE_INSERT_PPT_VIDEO_SOURCE_RT			= 10002
	, BE_INSERT_PPT_AUDIO_SOURCE_RT			= 10003
	, BE_INSERT_PPT_MEDIA_DESTINATION		= 10004
	, BE_INSERT_PPT_MEDIA_DESTINATION_RT	= 10005
	, BE_REMOVE_PPT_VIDEO_SOURCE			= 10006
	, BE_REMOVE_PPT_AUDIO_SOURCE			= 10007
	, BE_REMOVE_PPT_VIDEO_SOURCE_RT			= 10008
	, BE_REMOVE_PPT_AUDIO_SOURCE_RT			= 10009
	, BE_REMOVE_PPT_MEDIA_DESTINATION		= 10010
	, BE_REMOVE_PPT_MEDIA_DESTINATION_RT	= 10011
	, BE_DELIVER_EVENT_KEEP_ALIVE			= 10012
	, BE_DROP_USER							= 10013
};

enum PACKET_SOURCE_EVENT_TYPE : UINT16
{
	PSET_AUDIO_PACKET_FILTER			= 0
	, PSET_VIDEO_PACKET_FILTER			= 1
	, PSET_AUDIO_PACKET_PIN				= 2
	, PSET_VIDEO_PACKET_PIN				= 3
	, PSET_INSERT_PPT_SOURCE_INFO		= 10000
};

enum PACKET_SOURCE_EVENT_FILTER : UINT16
{
	PSEF_STOP							= 0
	, PSEF_PAUSE						= 1
	, PSEF_RUN							= 2
};

enum PACKET_SOURCE_EVENT_PIN : UINT16
{
	PSEP_ACTIVE							= 0
	, PSEP_END_OF_STREAM				= 1
	, PSEP_BEGIN_FLUSH					= 2
	, PSEP_END_FLUSH					= 3
	, PSEP_NEWSEGMENT					= 4
	, PSEP_RECEIVE						= 5
	, PSEP_INACTIVE						= 6
};

enum PACKET_DATA_BLOB_TYPE : UINT16
{
	PDBT_EVENT_HEADER		= 0
	, PDBT_EVENT_PACKET_HEADER	= 1
	, PDBT_EVENT_PACKET_PAYLOAD	= 2
	, PDBT_SERVER_EVENT_PAYLOAD = 10000
};

enum PACKET_HEADER_SEQUENCE : UINT16
{
	PHS_IP_HEADER				= 0
	, PHS_UDP_HEADER			= 1
	, PHS_EVENT_HEADER			= 2
	, PHS_EVENT_PACKET_HEADER	= 3
	, PHS_PACKET_DATA_BLOB		= 4
};
